name: Build ERPNext 16 (Oracle ARM)

on:
  push:
    branches: [ main ]
    paths:
      - "development/app.json"
      - "docker-bake.*"
      - "images/**"
  workflow_dispatch:

concurrency:
  group: build-frappe
  cancel-in-progress: true

env:
  BUILDKIT_PROGRESS: plain

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Prepare variables
        run: |
          OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          echo "REGISTRY_USER=ghcr.io/$OWNER" >> $GITHUB_ENV
          echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV
          APPS_JSON_BASE64=$(base64 -w 0 development/app.json)
          echo "APPS_JSON_BASE64=$APPS_JSON_BASE64" >> $GITHUB_ENV

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build ERPNext ARM64
        run: |
          docker buildx bake \
            -f docker-bake.hcl \
            -f docker-bake.override.hcl \
            erpnext \
            --set erpnext.platform=linux/arm64 \
            --set erpnext.args.FRAPPE_VERSION=version-16 \
            --set erpnext.args.ERPNEXT_VERSION=version-16 \
            --set erpnext.args.PYTHON_VERSION=3.14 \
            --set erpnext.args.NODE_VERSION=24 \
            --set erpnext.args.CYPRESS_INSTALL_BINARY=0 \
            --set erpnext.args.APPS_JSON_BASE64=${APPS_JSON_BASE64} \
            --set erpnext.tags=${REGISTRY_USER}/erpnext-custom:latest \
            --set erpnext.tags=${REGISTRY_USER}/erpnext-custom:${SHORT_SHA} \
            --set erpnext.cache-from=type=registry,ref=${REGISTRY_USER}/erpnext-custom:buildcache \
            --set erpnext.cache-to=type=registry,ref=${REGISTRY_USER}/erpnext-custom:buildcache,mode=max \
            --push
